### ISSUE TITLE
单个服务如何独立运行？

### ISSUE THREAD

**Issue by halower** [MarioLuLu7/microfrontend-admin#1]
我试了下，app1独立运行不了

**Comment by MarioLuLu7** [comment]
进入app1，安装App1的依赖，npm run serve就可以运行，不知道你具体出现了什么问题？

**Comment by halower** [comment]
进入app1，安装App1的依赖，npm run serve就可以运行,但是会显示空白异常页面，我在window/linux下都测试过，现象一样，但是如果是启动baseApp是可以切换app1,app2的，请教下这是为什么？
![20191216134830](https://user-images.githubusercontent.com/4995227/70882475-e01d4d80-200a-11ea-8419-c30273001ea9.png)

**Comment by MarioLuLu7** [comment]
因为子项目最终输出的是一个js文件而不是一个html文件，具体可看子项目的vue.config.js，baseApp加载的也是子项目的主入口(localhost:8077/app.js)，子项目单独访问是无法访问的。你可以配合baseapp添加子项目模块尝试运行。

**Comment by halower** [comment]
那这种就有悖于微前端独立部署的原则了，相互之间影响很大，子项目并不能达到自治

**Comment by MarioLuLu7** [comment]
子项目可以独立部署，主项目配置好后，子项目进行修改并不会影响主项目，只是需要通过主去访问而已，通过主项目来获取组装不同的子项目的页面和功能，把子项目微服务化并不违背微前端的原则。

**Comment by MarioLuLu7** [comment]
如果是因为单个子项目无法独立运行，可以在子项目下再加一个入口文件，配置好后构建时让其同时输出index.html和app.js即可。

**Comment by halower** [comment]
恩，这个项目非常好，你说的是这么回事，但是这个项目是有必要在子项目中直接输出index.html就完美了，这样的话多个团队开发的时候就可以直接调试自己的页面，不需要在主项目里进行配置在进行开发期的调试，因为有些场景确实需要做到开发时候的完全隔离

**Comment by MarioLuLu7** [comment]
加了参数，来控制输出形式。

**Comment by halower** [comment]
nice， good job
