### ISSUE TITLE
请问，如何单个打包部署

### ISSUE THREAD

**Issue by sunnybearmiah** [MarioLuLu7/microfrontend-admin#2]
请问，三个项目分别打包之后，如何部署的，能具体说说吗

**Comment by MarioLuLu7** [comment]
其实部署方式和普通的spa项目并没有差别，只是子项目最终暴露出来的入口不是一个html文件而是app.js这个文件（具体可以查看vue.config.js文件），然后使用nginx起出服务即可。

**Comment by limodou** [comment]
如果有css文件如何处理？

**Comment by MarioLuLu7** [comment]
> 如果有css文件如何处理？

有个插件postcss-selector-namespace，可以实现样式隔离，我之后会添加。
