### ISSUE TITLE
子项目单独运行貌似在浏览器打不开，是要依赖主项目环境？

### ISSUE THREAD

**Issue by zzkkui** [MarioLuLu7/microfrontend-admin#21]
子项目单独运行貌似在浏览器打不开，是要依赖主项目环境？

**Comment by MarioLuLu7** [comment]
在开发环境时，考虑到子项目不与 baseapp 交互时，不能运行子项目。可以控制 src/config/config.js 中 outputHtml 为 true 即可使其单独运行（此时不能进行微服务化）。
