### ISSUE TITLE
单独运行子项目

### ISSUE THREAD

**Issue by patgdut** [MarioLuLu7/microfrontend-admin#5]
在开发环境时，考虑到子项目不与 baseapp 交互时，不能运行子项目。可以控制 src/config/config.js 中 outputHtml 为 true 即可使其单独运行（此时不能进行微服务化）

你好，我根据你的文档设置，但是运行时空白，请问如何解决？

**Comment by MarioLuLu7** [comment]
fix the bug.
example：app1  open url  http://localhost:8077/#/app1
